### ISSUE TITLE
Hr detection

### ISSUE THREAD

**Issue by ll643989** [eml-eda/pytorch-benchmarks#3]
Hello, I have noticed your new article 'Feature-Level Cross-Attentional PPG and Motion Signal Fusion for Heart Rate Estimation', I am very interested in the idea of combining TCN and Attention in this job. Is the code open source?

**Comment by ABurrello** [comment]
Hello, unfortunately, it does not depend on us, but on the main authors of the article. I suggest to write to Dr. Panagiotis.
